# Generated by Django 5.0.4 on 2024-07-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chuongtrinh_daotao',
            fields=[
                ('Ma_CTDT', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_CTDT', models.CharField(max_length=100)),
                ('Ngay_quyet_dinh', models.DateField()),
                ('So_quyet_dinh', models.CharField(max_length=100)),
                ('Loai_hinh_dao_tao', models.CharField(max_length=100)),
                ('Tong_so_tin_chi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chuong_trinh_dao_tao',
            },
        ),
        migrations.CreateModel(
            name='Covan',
            fields=[
                ('Id_cv', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ho_ten_cv', models.CharField(max_length=100)),
                ('Ngay_sinh_cv', models.DateField()),
                ('Gioi_tinh_cv', models.CharField(max_length=100)),
                ('Dia_chi_cv', models.CharField(max_length=100)),
                ('Email_cv', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'co_van',
            },
        ),
        migrations.CreateModel(
            name='Hockychuongtrinhdaotao',
            fields=[
                ('Ma_HK_CTDT', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_HK_CTDT', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hk_ctdt',
            },
        ),
        migrations.CreateModel(
            name='Hockynienkhoa',
            fields=[
                ('Ma_hk_nien_khoa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_hk_nien_khoa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hk_nien_khoa',
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('Ma_khoa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_khoa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'khoa',
            },
        ),
        migrations.CreateModel(
            name='Loaihocphan',
            fields=[
                ('Ma_loai_hp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_loai_hp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loai_hp',
            },
        ),
        migrations.CreateModel(
            name='Nhommon',
            fields=[
                ('Ma_nhom_mon', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_nhom_mon', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nhom_mon',
            },
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('User_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('admin', 'admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
            ],
            options={
                'db_table': 'tai_khoan',
            },
        ),
        migrations.CreateModel(
            name='Bangdiem',
            fields=[
                ('Ma_bang_diem', models.AutoField(primary_key=True, serialize=False)),
                ('Diem_trung_binh_hoc_ky', models.CharField(max_length=100)),
                ('Diem_tich_luy_he_4', models.CharField(max_length=100)),
                ('Ma_hk_nien_khoa', models.ForeignKey(db_column='Ma_hk_nien_khoa', on_delete=django.db.models.deletion.CASCADE, to='Admin.hockynienkhoa')),
            ],
            options={
                'db_table': 'bang_diem',
            },
        ),
        migrations.CreateModel(
            name='Bomon',
            fields=[
                ('Ma_bo_mon', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_bo_mon', models.CharField(max_length=100)),
                ('Ma_khoa', models.ForeignKey(db_column='Ma_khoa', on_delete=django.db.models.deletion.CASCADE, to='Admin.khoa')),
            ],
            options={
                'db_table': 'bo_mon',
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('Ma_lop', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_lop', models.CharField(max_length=100)),
                ('Id_cv', models.ForeignKey(db_column='Id_cv', on_delete=django.db.models.deletion.CASCADE, to='Admin.covan')),
                ('Ma_CTDT', models.ForeignKey(db_column='Ma_CTDT', on_delete=django.db.models.deletion.CASCADE, to='Admin.chuongtrinh_daotao')),
            ],
            options={
                'db_table': 'lop',
            },
        ),
        migrations.CreateModel(
            name='Monhoc',
            fields=[
                ('Ma_mon_hoc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_mon_hoc', models.CharField(max_length=100)),
                ('Tin_chi', models.IntegerField()),
                ('Linh_vuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.monhoc')),
            ],
            options={
                'db_table': 'mon_hoc',
            },
        ),
        migrations.CreateModel(
            name='Chitiet_bangdiem',
            fields=[
                ('Ma_CTBD', models.AutoField(primary_key=True, serialize=False)),
                ('Diem_he_4', models.CharField(max_length=100)),
                ('Diem_he_10', models.CharField(max_length=100)),
                ('Diem_he_10_lan_2', models.CharField(max_length=100)),
                ('Ma_bang_diem', models.ForeignKey(db_column='Ma_bang_diem', on_delete=django.db.models.deletion.CASCADE, to='Admin.bangdiem')),
                ('Ma_mon_hoc', models.ForeignKey(db_column='Ma_mon_hoc', on_delete=django.db.models.deletion.CASCADE, to='Admin.monhoc')),
            ],
            options={
                'db_table': 'chi_tiet_bang_diem',
            },
        ),
        migrations.CreateModel(
            name='Nganhdaotao',
            fields=[
                ('Ma_nganh', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ten_nganh', models.CharField(max_length=100)),
                ('Ma_bo_mon', models.ForeignKey(db_column='Ma_bo_mon', on_delete=django.db.models.deletion.CASCADE, to='Admin.bomon')),
            ],
            options={
                'db_table': 'nganh_dao_tao',
            },
        ),
        migrations.AddField(
            model_name='chuongtrinh_daotao',
            name='Ma_nganh',
            field=models.ForeignKey(db_column='Ma_nganh', on_delete=django.db.models.deletion.CASCADE, to='Admin.nganhdaotao'),
        ),
        migrations.CreateModel(
            name='Sinhvien',
            fields=[
                ('MSSV', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ho_ten_sv', models.CharField(max_length=100)),
                ('Dia_chi_sv', models.CharField(max_length=100)),
                ('Gioi_tinh_sv', models.CharField(max_length=100)),
                ('Email_sv', models.CharField(max_length=100)),
                ('Ngay_sinh_sv', models.DateField()),
                ('Ma_lop', models.ForeignKey(db_column='Ma_lop', on_delete=django.db.models.deletion.CASCADE, to='Admin.lop')),
            ],
            options={
                'db_table': 'sinh_vien',
            },
        ),
        migrations.AddField(
            model_name='bangdiem',
            name='MSSV',
            field=models.ForeignKey(db_column='MSSV', on_delete=django.db.models.deletion.CASCADE, to='Admin.sinhvien'),
        ),
        migrations.CreateModel(
            name='thuoc_ctdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_CTDT', models.ForeignKey(db_column='Ma_CTDT', on_delete=django.db.models.deletion.CASCADE, to='Admin.chuongtrinh_daotao')),
                ('Ma_HK_CTDT', models.ForeignKey(db_column='Ma_HK_CTDT', on_delete=django.db.models.deletion.CASCADE, to='Admin.hockychuongtrinhdaotao')),
                ('Ma_loai_hp', models.ForeignKey(db_column='Ma_loai_hp', on_delete=django.db.models.deletion.CASCADE, to='Admin.loaihocphan')),
                ('Ma_mon_hoc', models.ForeignKey(db_column='Ma_mon_hoc', on_delete=django.db.models.deletion.CASCADE, to='Admin.monhoc')),
                ('Ma_nhom_mon', models.ForeignKey(db_column='Ma_nhom_mon', on_delete=django.db.models.deletion.CASCADE, to='Admin.nhommon')),
            ],
            options={
                'db_table': 'thuoc_ctdt',
            },
        ),
    ]
